
workflows:
  ios-release:
    name: iOS Release Build
    environment:
      vars:
        BUNDLE_ID: "com.glynpool.spin2dine"
        APP_STORE_CONNECT_EMAIL: "glyn.pool@baronservices.com"
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing dependencies"
      - name: Build app
        script: |
          xcodebuild -scheme Spin2DineApp -configuration Release
    artifacts:
      - build/ios/Release/**/*.ipa
